# Generated by Django 5.2.6 on 2025-09-05 21:23

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EVMChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('chain_id', models.IntegerField(unique=True)),
                ('rpc_url', models.URLField()),
                ('explorer_url', models.URLField(blank=True, null=True)),
                ('native_currency_symbol', models.CharField(default='ETH', max_length=10)),
                ('native_currency_name', models.CharField(default='Ethereum', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_testnet', models.BooleanField(default=False)),
                ('block_time_seconds', models.IntegerField(default=12)),
                ('gas_price_gwei', models.DecimalField(decimal_places=2, default=20.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'EVM Chain',
                'verbose_name_plural': 'EVM Chains',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=20)),
                ('address', models.CharField(blank=True, max_length=42, null=True)),
                ('decimals', models.PositiveSmallIntegerField(default=18)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_native', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('min_transfer_amount', models.DecimalField(decimal_places=18, default=Decimal('0.001'), max_digits=36)),
                ('max_transfer_amount', models.DecimalField(decimal_places=18, default=Decimal('1000000'), max_digits=36)),
                ('transfer_fee_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.1'), max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='wallet.evmchain')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
                'unique_together': {('chain', 'address')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(db_index=True, max_length=66, unique=True)),
                ('from_address', models.CharField(max_length=42)),
                ('to_address', models.CharField(max_length=42)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=36)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer'), ('swap', 'Swap'), ('stake', 'Stake'), ('unstake', 'Unstake')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('gas_used', models.BigIntegerField(blank=True, null=True)),
                ('gas_price', models.DecimalField(blank=True, decimal_places=18, max_digits=36, null=True)),
                ('gas_fee', models.DecimalField(blank=True, decimal_places=18, max_digits=36, null=True)),
                ('block_number', models.BigIntegerField(blank=True, null=True)),
                ('block_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.evmchain')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.token')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.CreateModel(
            name='ReferralReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=18, max_digits=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_rewards_given', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_rewards_received', to=settings.AUTH_USER_MODEL)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_rewards', to='wallet.token')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_rewards', to='wallet.transaction')),
            ],
            options={
                'verbose_name': 'Referral Reward',
                'verbose_name_plural': 'Referral Rewards',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=42, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='wallet.evmchain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
            },
        ),
        migrations.CreateModel(
            name='TokenBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=36)),
                ('frozen_balance', models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=36)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='wallet.token')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_balances', to='wallet.wallet')),
            ],
            options={
                'verbose_name': 'Token Balance',
                'verbose_name_plural': 'Token Balances',
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['hash'], name='wallet_tran_hash_b30b7d_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'status'], name='wallet_tran_user_id_9b1f68_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['chain', 'status'], name='wallet_tran_chain_i_32c7e1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='wallet',
            unique_together={('user', 'chain')},
        ),
        migrations.AlterUniqueTogether(
            name='tokenbalance',
            unique_together={('wallet', 'token')},
        ),
    ]
