# Generated by Django 5.2.6 on 2025-09-06 10:35

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(db_index=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chat',
                'verbose_name_plural': 'Chats',
            },
        ),
        migrations.CreateModel(
            name='ChatActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('reward', 'Token Reward'), ('chat_created', 'Chat Created'), ('chat_updated', 'Chat Updated'), ('wallet_created', 'Wallet Created'), ('balance_updated', 'Balance Updated')], max_length=20)),
                ('description', models.TextField(max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='squad.chat')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Activity',
                'verbose_name_plural': 'Chat Activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatTokenBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=36)),
                ('frozen_balance', models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=36)),
                ('min_reward_amount', models.DecimalField(decimal_places=18, default=Decimal('0.001'), max_digits=36)),
                ('max_reward_amount', models.DecimalField(decimal_places=18, default=Decimal('1.0'), max_digits=36)),
                ('reward_enabled', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_balances', to='wallet.token')),
            ],
            options={
                'verbose_name': 'Chat Token Balance',
                'verbose_name_plural': 'Chat Token Balances',
            },
        ),
        migrations.CreateModel(
            name='ChatReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=18, max_digits=36)),
                ('message_id', models.BigIntegerField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='squad.chat')),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rewards_given', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rewards_received', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rewards', to='wallet.transaction')),
                ('token_balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='squad.chattokenbalance')),
            ],
            options={
                'verbose_name': 'Chat Reward',
                'verbose_name_plural': 'Chat Rewards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_wallets', to='wallet.evmchain')),
                ('chat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='squad.chat')),
            ],
            options={
                'verbose_name': 'Chat Wallet',
                'verbose_name_plural': 'Chat Wallets',
            },
        ),
        migrations.AddField(
            model_name='chattokenbalance',
            name='chat_wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_balances', to='squad.chatwallet'),
        ),
        migrations.AlterUniqueTogether(
            name='chattokenbalance',
            unique_together={('chat_wallet', 'token')},
        ),
    ]
