# Generated by Django 5.2.6 on 2025-09-05 22:36

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('max_members', models.PositiveIntegerField(default=50)),
                ('is_public', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('banner_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('members', models.ManyToManyField(blank=True, related_name='squads', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_squads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Squad',
                'verbose_name_plural': 'Squads',
            },
        ),
        migrations.CreateModel(
            name='SquadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('member_joined', 'Member Joined'), ('member_left', 'Member Left'), ('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('drop', 'Token Drop'), ('squad_created', 'Squad Created'), ('squad_updated', 'Squad Updated')], max_length=20)),
                ('description', models.TextField(max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='squad.squad')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='squad_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Squad Activity',
                'verbose_name_plural': 'Squad Activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SquadWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=42, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squad_wallets', to='wallet.evmchain')),
                ('squad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='squad.squad')),
            ],
            options={
                'verbose_name': 'Squad Wallet',
                'verbose_name_plural': 'Squad Wallets',
            },
        ),
        migrations.CreateModel(
            name='SquadMemberBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=36)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_balances', to='squad.squad')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_balances', to='wallet.token')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squad_balances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Squad Member Balance',
                'verbose_name_plural': 'Squad Member Balances',
                'unique_together': {('user', 'token', 'squad')},
            },
        ),
        migrations.CreateModel(
            name='SquadTokenBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=36)),
                ('frozen_balance', models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=36)),
                ('min_drop_amount', models.DecimalField(decimal_places=18, default=Decimal('0.001'), max_digits=36)),
                ('max_drop_amount', models.DecimalField(decimal_places=18, default=Decimal('1.0'), max_digits=36)),
                ('drop_enabled', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squad_balances', to='wallet.token')),
                ('squad_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_balances', to='squad.squadwallet')),
            ],
            options={
                'verbose_name': 'Squad Token Balance',
                'verbose_name_plural': 'Squad Token Balances',
                'unique_together': {('squad_wallet', 'token')},
            },
        ),
    ]
