# Generated by Django 5.2.6 on 2025-09-05 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squad', '0002_remove_allianceinvitation_alliance_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alliance',
        ),
    ]
